cicd.yml syntax error 수정

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -44,20 +44,23 @@ jobs:
         run: |
           STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.TAKA_SERVER_IP }}/env")
           echo $STATUS
-          if [ $STATUS = 200 ]; then
+          if [ "$STATUS" = "200" ]; then
             CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.TAKA_SERVER_IP }}/env")
           else
-            CURRENT_UPSTREAM=green
+            CURRENT_UPSTREAM="green"
           fi
-          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
-          if [ $CURRENT_UPSTREAM = blue ]; then
+          echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
+          if [ "$CURRENT_UPSTREAM" = "blue" ]; then
             echo "CURRENT_PORT=8080" >> $GITHUB_ENV
             echo "STOPPED_PORT=8081" >> $GITHUB_ENV
             echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-          else [ $CURRENT_UPSTREAM = green ]; then
+          elif [ "$CURRENT_UPSTREAM" = "green" ]; then
             echo "CURRENT_PORT=8081" >> $GITHUB_ENV
             echo "STOPPED_PORT=8080" >> $GITHUB_ENV
             echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
           fi
 
       - name: Docker compose
